package model;

public enum MagicEffects {
    //spells
    SPECIAL_SUMMON_FROM_GRAVEYARD,
    ADD_FIELD_SPELL_TO_HAND,
    DRAW_TWO_CARD,
    DESTROY_ALL_RIVAL_MONSTERS,
    CONTROL_ONE_RIVAL_MONSTER,
    DESTROY_ALL_RIVAL_SPELL_TRAPS,
    SWORD_OF_REVEALING_LIGHT,
    DESTROY_ALL_MONSTERS,
    DRAW_CARD_IF_MONSTER_DESTROYED,
    INCREASE_LP_IF_SPELL_ACTIVATED,
    MESSENGER_OF_PEACE,
    TWIN_TWISTERS,
    DESTROY_SPELL_OR_TRAP,
    RING_OF_DEFENSE,
    YAMI,
    FOREST,
    CLOSED_FOREST,
    UMIIRUKA,
    SWORD_OF_DARK_DESTRUCTION,
    BLACK_PENDANT,
    UNITED_WE_STAND,
    MAGNUM_SHIELD,
    RITUAL_SUMMON,

    //traps
    MAGIC_CYLINDER,
    DESTROY_ALL_RIVAL_FACE_UP_CARDS,
    MIND_CRUSH,
    TRAP_HOLE,
    CANT_DRAW,
    NEGATE_ATTACK_PHASE,
    SOLEMN_WARNING,
    MAGIC_JAMMER,
    CALL_OF_THE_HAUNTED
}
