package model;

public enum MonsterEffects {
    SET_ATTACK,
    COMBINE_LEVELS_OF,
    SELECT_FACE_UP_MONSTERS,
    DISPOSABLE,
    ADD_ATTACK_TO_FACE_UP_CARDS,
    CAN_NOT_BE_ATTACKED_WHEN_WE_HAVE_ANOTHER_MONSTER,
    DESTROY_ATTACKER_CARD_IF_DESTROYED,
    ZERO_ATTACK_POWER_FOR_ATTACKER_ON_THAT_TURN,
    CALLABLE_BY_RITUAL_SUMMON,
    DESTROY_ONE_OF_RIVAL_MONSTERS_AFTER_FLIP,
    SCAN_A_DESTROYED_MONSTER,
    CANT_BE_DESTROYED_IN_NORMAL_ATTACK,
    BEAST_KING_BARBAROS,
    DECREASE_ATTACK_POWER_IN_NORMAL_SUMMON,
    NEUTRAL_ONE_ATTACK_IN_EACH_TURN,
    SPECIAL_SUMMON_A_NORMAL_CYBERSE_MONSTER,
    RIVAL_CANT_ACTIVE_TRAP,
    HERALD_OF_CREATION,
    DRAW_CARD_FROM_GRAVEYARD,
    DISPOSABLE_IN_ONE_TURN,
    LPS_DOESNT_CHANGE,
    TERRATIGER,
    SPECIAL_SUMMON_BY_REMOVE_CARD_FROM_HAND
}
