package controller.responses;

public enum DeckMenuResponses {
    DECK_CREATE_SUCCESSFUL,
    DECK_NAME_ALREADY_EXISTS,
    DECK_DELETE_SUCCESSFUL,
    DECK_NAME_NOT_EXIST,
    DECK_ACTIVATE_SUCCESSFUL,
    CARD_ADD_TO_DECK_SUCCESSFUL,
    CARD_NAME_NOT_EXIST,
    DECK_FULL,
    MAX_SIZE_IDENTICAL_CARDS_ALREADY_IN_DECK,
    CARD_REMOVE_SUCCESSFUL,
    CARD_NAME_NOT_EXIST_IN_DECK,
    SHOW_ALL_DECKS,
    SHOW_DECK,
    SHOW_ALL_CARDS
}
