package controller.responses;

public enum DuelMenuResponses {
    NO_PLAYER_WITH_THIS_USERNAME_EXISTS,
    CURRENT_PLAYER_HAS_NO_ACTIVE_DECK,
    OPPONENT_PLAYER_HAS_NO_ACTIVE_DECK,
    INVALID_CURRENT_PLAYER_DECK,
    INVALID_OPPONENT_PLAYER_DECK,
    UNSUPPORTED_ROUND_NUMBER,
    GAME_STARTED_SUCCESSFULLY,
    INVALID_SELECTION,
    SELECTION_NO_CARD_FOUND,
    CARD_SELECTED;
}
