package controller.responses;

public enum LoginMenuResponses {
    USER_CREATE_SUCCESSFUL,
    USER_USERNAME_ALREADY_EXISTS,
    USER_NICKNAME_ALREADY_EXISTS,
    USER_LOGIN_SUCCESSFUL,
    USER_USERNAME_PASSWORD_NOT_MATCHED,
    USER_LOGOUT_SUCCESSFUL
}
